#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

case "$1" in
  help | docker-helper:help)
    help_content_func() {
      #shellcheck disable=SC2034
      declare desc="return help_content string"

      cat<<help_content
    docker-helper:pull <image> , Pull <image>
help_content
    }

    if [[ $1 = "docker-helper:help" ]]; then
      echo -e 'Usage: dokku docker-helper[:COMMAND] [<image>]'
      echo ''
      echo 'Run Docker commands.'
      echo ''
      echo 'Example: '
      echo '$ dokku docker-helper:pull <image>'
      echo ''
      echo -e 'Additional commands:'
      help_content_func | sort | column -c2 -t -s,
    else
      cat<<help_desc
    docker-helper, Plugin for executing docker commands
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
