#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

docker_helper_pull_cmd() {
  #shellcheck disable=SC2034
  declare desc="Run docker pull"
  local cmd="docker-helper:pull"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  set -- $cmd $@

  DOCKER_IMAGE="$2"
  [[ -z "${DOCKER_IMAGE}" ]] && dokku_log_fail "Please specify a docker image to pull"
  "$DOCKER_BIN" pull "${DOCKER_IMAGE}"
}

docker_helper_pull_cmd "$@"
